# Generated by Django 6.0.6 on 2026-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Product name')),
                ('price', models.FloatField(verbose_name='Product price')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Product create date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Product update date')),
                ('description', models.TextField(verbose_name='Product description')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Product image')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
